FROM docker.io/library/httpd:alpine
# Creamos un index de prueba para verificar el clúster
RUN echo "<h1>Hola UNIR - Despliegue en Kubernetes (AKS) Exitoso</h1>" > /usr/local/apache2/htdocs/index.html

